### ISSUE TITLE
Update details -- course page 

### ISSUE THREAD

**Issue by gauravjain99** [CodeDocsJECRC/codedocsjecrc.github.io#14]
Update the details on course page

**Comment by maddhruv** [comment]
also change the time to 1-3PM @akshaysharma2277

**Comment by maddhruv** [comment]
Updated: 
Class - 1-2 - Web Development, Tutor - Dhruv Jain (6CS)
Class - 2-3 - Android Development, Tutor - Kandarp Gupta, Aayush Goyal, Kandarp Gupta (6CS)

**Comment by akshaysharma2277** [comment]
Two Kandarp Gupta????

**Comment by maddhruv** [comment]
Prateek Vijayvergiya

**Comment by maddhruv** [comment]
@akshaysharma2277 also update the timings for both the classes
> Class - 1-2 - Web Development, Tutor - Dhruv Jain (6CS)
Class - 2-3 - Android Development, Tutor - Kandarp Gupta, Aayush Goyal, Prateek Vijayvergiya (6CS)

**Comment by maddhruv** [comment]
@akshaysharma2277 can this be closed?
