### ISSUE TITLE
Update Classes schedule

### ISSUE THREAD

**Issue by maddhruv** [CodeDocsJECRC/codedocsjecrc.github.io#21]
Update all the classes scheduled for upcoming classes (Lecture 2, 3, 4, 5) for both Web and Android Development.

Also, update Instructor for Web Lecture 2 - Amrit Srivastava

**Comment by aditya81070** [comment]
I want to work on it.

**Comment by aditya81070** [comment]
What should be the class shedule?

**Comment by maddhruv** [comment]
Lecture 2-5 are on W, Th, F, Sa respectively

**Comment by maddhruv** [comment]
Also
Coordinate with instructors to know the instructor taking a clas

**Comment by maddhruv** [comment]
@CodeDocsJECRC/instructors team can be contacted whosoever is working on this

**Comment by aditya81070** [comment]
Okay, I am working on it.

**Comment by accakks** [comment]
Ref #24
