### ISSUE TITLE
Primary changes required for the website.

### ISSUE THREAD

**Issue by amritsrivastava** [CodeDocsJECRC/codedocsjecrc.github.io#26]
**Please mention all the initial changes we required before orientation and course 201.**

#### Some of them are 
- Banner Update
- Update Slack Link 
- Update Social Media Handels 
- CD201 Couse Update
- Calender Update

**Comment by aditya81070** [comment]
@amritsrivastava  I have done following changes and created a pull request:-
* Update slack link
* Update Social media handles
