### ISSUE TITLE
Build the Team page

### ISSUE THREAD

**Issue by maddhruv** [CodeDocsJECRC/codedocsjecrc.github.io#5]
add all @CodeDocsJECRC/community-committee team members to the team page with general details.

**Comment by akshaysharma2277** [comment]
Updated, please review the pr.

**Comment by aditya81070** [comment]
What type of team page is required? A simple page that contains all member's info like profile card?

**Comment by akshaysharma2277** [comment]
Build the page which contains all the info about team members i.e pic, name, role, branch and year. using jekyll.

**Comment by maddhruv** [comment]
We are not yet clear with adding all individual members to the list or just the Community Committee and active members

**Comment by maddhruv** [comment]
But before that we wish to get a dummy page with profile cards and may be individual profile pages like `/profile/maddhruv` for a brief Knowledge of the member

**Comment by amritsrivastava** [comment]
It's better we create cards for individual profiles, once we completed this after that we will add a button of "View Profile" and then link it to the individual profile pages.

**Comment by maddhruv** [comment]
https://developers.google.com/web/resources/contributors/ can be referred

**Comment by accakks** [comment]
Ref #24
