### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by maddhruv** [CodeDocsJECRC/codedocsjecrc.github.io#9]
suggest questions to add on the faq page

**Comment by maddhruv** [comment]
cc @CodeDocsJECRC/community-committee

**Comment by accakks** [comment]
1. How can I be a part of Codedocs?
2. Can a first-year student with no coding experience become a part of Codedocs?
3. I'm from *blank* branch, Can I join Codedocs?
(_*Joining=_ Being a member, not volunteer or community member. )
----------------------------------------------------------------------------------------------
4. How can I volunteer in Codedocs?
5. I'm interested in taking classes. How should I go about it?
6. Can I propose a collaborative project on Codedocs?
7. I want to conduct *blank* event (related to Computer Science), can Codedocs help me in that?
8. What is the meaning of open community? 
9.  How can I stay updated with Codedocs events and activities schedule?
10. How do I register for Codedocs courses?
11. What do we get from completing Codedocs courses?
12. I have a problem with some Codedocs member/event, where can I complain?
-----------------------------------------------------------------------------------------------------------------------
**Will add more as I remember. I can write answers to the ones approved**

**Comment by maddhruv** [comment]
You have covered many of the FAQs.
Can you tell me quite about them also?
Like what is the difference between 5th and 10th
> (*Joining= Being a member, not volunteer or community member. )

what is meant by being a member but not a member :thinking: 


We will wait for more information and decisions to come upon, will appreciate your PR

**Comment by accakks** [comment]
> Like what is the difference between 5th and 10th
5th is If someone wants to take classes as an instructor. I should have clarified it. While 10th is a student.

> (*Joining= Being a member, not volunteer or community member. )
Here joining does not mean volunteering, but getting the advantage of classes or events as an attendee only. People can be confused if Codedocs takes auditions like other clubs too. So maybe we can clarify anyone can join Codedocs, as an attendee, and all the attendee can step up to volunteer. 

Should I make PRs after writing the answers or first discuss here? @maddhruv @ShivSoni5

**Comment by maddhruv** [comment]
We should collect all the questions first and then you can make a PR.
All the above questions are quite complete but we should discuss it with the CommComm

**Comment by accakks** [comment]
Ref #24
